### ISSUE TITLE
Might need to use object streams for everything

### ISSUE THREAD

**Issue by Malikil** [Malikil/CSIS3475#32]
The object streams are connecting properly, the string streams don't seem to be doing so. It may be worth considering just using the object streams for everything, then cast to String if needed.

**Comment by Ladoli** [comment]
Makes it easier and more consistent too. That way it only needs to send one "message" each time. The object sent will have the command enum and other fields could be inside it as needed such as String for message, Table name for creating/deleting and entries for updating.

**Comment by Malikil** [comment]
Messages are now wrapped in a single class, which is sent once. Eliminating the need to string streams anyways.
